# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/hdl_things/uart_com/uart_com.cache/wt [current_project]
set_property parent.project_path G:/hdl_things/uart_com/uart_com.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths C:/Xilinx/vivado-boards-master/new/board_files [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo g:/hdl_things/uart_com/uart_com.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/uart_tx.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/clk_gen.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/uart_rx.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/uart.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/uart_nexys.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/hex2ssd.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/DispMan.v
  G:/hdl_things/uart_com/uart_com.srcs/sources_1/new/RefreshClk.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/hdl_things/uart_com/uart_com.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files G:/hdl_things/uart_com/uart_com.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top uart_nexys -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef uart_nexys.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file uart_nexys_utilization_synth.rpt -pb uart_nexys_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
